README.md
Fix to #71. @keilw I have closed PR #72 since ip validation fails (document edited on github).
Would like to update travis-ci build status link? that may requires setup change with travis-ci.
Also, what is the plan for spec link https://javaee.github.io/security-spec. it can be imported to gh-pages of this project.
@ivargrimstad @arjantijms updated PR with https link
=> Update README.md API link to https

pom.xml
https://github.com/eclipse-ee4j/security-api/issues/76
=> Addressing #76 Version number in POM?

src/main/java/javax/security/enterprise/CallerPrincipal.java, src/main/java/javax/security/enterprise/identitystore/IdentityStorePermission.java
=> fixes two warnings

src/main/java/javax/security/enterprise/authentication/mechanism/http/LoginToContinue.java, src/main/java/javax/security/enterprise/authentication/mechanism/http/RememberMe.java, src/test/java/org/glassfish/security/AnnotationLiteralTest.java
As suggested by @keilw changed `of()` to `builder()`.
=> #82 - Changed of to builder

pom.xml
fixes #94 github issue
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
=> Update artifactId and groupID

.travis.yml, pom.xml
Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>
=> EE4J_8 release prepare (dependencies in pom.xml updated to jakarta.*)

src/main/java/javax/security/enterprise/CallerPrincipal.java
Addresses https://github.com/eclipse-ee4j/security-api/issues/102.
=> Made CallerPrincipal Serializable

pom.xml
=> Several pom fixes, but most importantly blocking 1.6.1 JACC

pom.xml
=> Set version to 1.0.2, remove duplicate plugin, fix javadoc version

CONTRIBUTING.md, README.md, pom.xml, src/main/java/javax/security/enterprise/AuthenticationException.java, src/main/java/javax/security/enterprise/AuthenticationStatus.java, src/main/java/javax/security/enterprise/SecurityContext.java, src/main/java/javax/security/enterprise/authentication/mechanism/http/AutoApplySession.java, src/main/java/javax/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanism.java, src/main/java/javax/security/enterprise/authentication/mechanism/http/HttpMessageContext.java, src/main/java/javax/security/enterprise/authentication/mechanism/http/LoginToContinue.java, src/main/java/javax/security/enterprise/authentication/mechanism/http/RememberMe.java, src/main/java/javax/security/enterprise/credential/RememberMeCredential.java, src/main/java/javax/security/enterprise/credential/package-info.java, src/main/java/javax/security/enterprise/identitystore/DatabaseIdentityStoreDefinition.java, src/main/java/javax/security/enterprise/identitystore/IdentityStore.java, src/main/java/javax/security/enterprise/identitystore/IdentityStoreHandler.java, src/main/java/javax/security/enterprise/identitystore/LdapIdentityStoreDefinition.java, src/main/java/javax/security/enterprise/identitystore/RememberMeIdentityStore.java, src/main/java/javax/security/enterprise/identitystore/package-info.java, src/main/java/javax/security/enterprise/package-info.java
=> #124 Prepare Jakarta Security for Jakarta EE 8 Release 

README.md
=> Update readme javadoc to Jakarta GAV

api/pom.xml
Note that this rev temporarily requires building with -Pstaging until the staged versions have been released.
=> #124 Prepare for 1.0.2 release - update deps to staged versions

api/pom.xml, api/src/main/javadoc/doc-files/speclicense.html
=> Update to latest Jakarta EE 8 requirements

spec/src/main/asciidoc/security-spec.adoc
=> Update doctitle by removing version

spec/src/main/asciidoc/license-efsl.adoc
=> Added Eclipse copyright to spec doc

api/pom.xml
=> Update to new Jakarta Authorization maven coordinates

spec/src/main/asciidoc/preface.adoc
=> Updated Preface with Jakarta people involved

spec/src/main/asciidoc/authenticationMechanism.adoc, spec/src/main/asciidoc/bibliography.adoc, spec/src/main/asciidoc/concepts.adoc
=> Update spec refs for authentication, authorization and expression lan.

api/pom.xml, pom.xml, spec/pom.xml
=> Update versions in pom to latest

api/pom.xml, pom.xml, spec/pom.xml
=> #156 Prepare for RC1 release

api/pom.xml, api/src/main/java/jakarta/security/enterprise/SecurityContext.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/CustomFormAuthenticationMechanismDefinition.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/FormAuthenticationMechanismDefinition.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/LoginToContinue.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/RememberMe.java
#156 Updated CDI dependency to Jakarta version
* Removed EJB dependency which wasn't a real dependency
* Using jakarta.* for EJB javadoc reference
=> #156 Updated CDI dependency to Jakarta version

api/src/main/javadoc/doc-files/speclicense.html, spec/src/main/asciidoc/license-efsl.adoc
Signed-off-by: Miguel Serra <Miguel.Serra@criticaltechworks.com>
=> Update EFSL for Specifications and Javadoc. solves #168

api/pom.xml, pom.xml, spec/pom.xml
=> Version back to snapshot, removed unneeded plugin, updated versions

api/pom.xml, spec/pom.xml
=> Update dependency versions in pom

api/pom.xml, spec/src/main/asciidoc/license-efsl.adoc
=> Several fixes

spec/pom.xml
Signed-off-by: Jean-Louis Monteiro <jlmonteiro@tomitribe.com>
=> Add jakarta- prefix to file names

api/src/main/java/jakarta/security/enterprise/AuthenticationStatus.java, api/src/main/java/jakarta/security/enterprise/SecurityContext.java, api/src/main/java/jakarta/security/enterprise/credential/Password.java, api/src/main/java/jakarta/security/enterprise/identitystore/IdentityStore.java, pom.xml, spec/pom.xml
=> White space and versions

api/pom.xml, spec/pom.xml
Some config changes due to breaking changes in v2.
See https://docs.asciidoctor.org/maven-tools/latest/plugin/v2-migration-guide/
=> Update dependencies, specifically of asciidoc

api/pom.xml, pom.xml, spec/pom.xml
=> Switch master over to 3.0

api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanismWrapper.java
=> #193 Add wrapper for HttpAuthenticationMechanism

api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/AutoApplySession.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/LoginToContinue.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/RememberMe.java
=> #196 - Add missing annotation literals to interceptor bindings

api/src/main/java/jakarta/security/enterprise/CallerPrincipal.java
=> Move latest copyright to top, to keep copyright plugin happy.

api/pom.xml, spec/pom.xml
=> Update dependencies in poms and copyright year

api/src/main/java/jakarta/security/enterprise/identitystore/ClaimsDefinition.java, api/src/main/java/jakarta/security/enterprise/identitystore/DisplayType.java, api/src/main/java/jakarta/security/enterprise/identitystore/LogoutDefinition.java, api/src/main/java/jakarta/security/enterprise/identitystore/OpenIdAuthenticationDefinition.java, api/src/main/java/jakarta/security/enterprise/identitystore/OpenIdProviderMetadata.java, api/src/main/java/jakarta/security/enterprise/identitystore/PromptType.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/AccessToken.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/Claims.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/IdentityToken.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/JwtClaims.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/OpenIdClaims.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/OpenIdConstant.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/OpenIdContext.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/RefreshToken.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/Scope.java
=> Fix the license so the API actually builds

api/pom.xml, api/src/main/java/jakarta/security/enterprise/identitystore/OpenIdAuthenticationDefinition.java
=> Fix javadoc

api/pom.xml
=> Fix authentication and authorization versions

api/pom.xml, api/src/main/java/module-info.java
=> 184 Add module-info

api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/LoginToContinue.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/OpenIdAuthenticationMechanismDefinition.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/openid/ClaimsDefinition.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/openid/DisplayType.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/openid/LogoutDefinition.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/openid/OpenIdConstant.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/openid/OpenIdProviderMetadata.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/openid/PromptType.java, api/src/main/java/jakarta/security/enterprise/identitystore/LdapIdentityStoreDefinition.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/IdentityToken.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/JwtClaims.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/OpenIdClaims.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/OpenIdContext.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/RefreshToken.java, api/src/main/java/jakarta/security/enterprise/identitystore/openid/Scope.java, api/src/main/java/module-info.java
=> Reorg packages for OpenID feature

api/src/main/java/jakarta/security/enterprise/identitystore/openid/OpenIdContext.java
the HttpAuthenticationMechanism already has this.
=> Remove the logout method from the OpenIdContext

api/pom.xml, spec/pom.xml
=> Update versions in pom

tck/LICENSE.md, tck/LICENSE_EFTL.md, tck/old-tck/run/pom.xml, tck/pom.xml, tck/zip.xml
=> Add assembly file to zip entire TCK

tck/old-tck/build/pom.xml
=> Set PATH and ANT_HOME when building old TCK

tck/pom.xml
=> Add aggregate failsafe report for TCK run

tck/pom.xml
=> Update reporting plugin

api/src/main/javadoc/doc-files/speclicense.html
=> Revert previous unnecessary update to speclicense

tck/app-custom-identity-store-handler/pom.xml, tck/app-custom-rememberme/pom.xml, tck/app-custom-session/pom.xml, tck/app-custom/pom.xml, tck/app-db/pom.xml, tck/app-jaxrs/pom.xml, tck/app-ldap/pom.xml, tck/app-ldap2/pom.xml, tck/app-ldap3/pom.xml, tck/app-mem-basic/pom.xml, tck/app-mem-customform/pom.xml, tck/app-mem-form/pom.xml, tck/app-mem/pom.xml, tck/app-multiple-store-backup/app-openid2/pom.xml, tck/app-multiple-store-backup/pom.xml, tck/app-multiple-store/pom.xml, tck/app-openid/pom.xml, tck/app-openid2/pom.xml, tck/app-openid3/pom.xml, tck/app-securitycontext-auth/pom.xml, tck/app-securitycontext-customprincipal/pom.xml, tck/app-securitycontext/pom.xml
=> Update common dependency to use project placeholder

spec/src/main/asciidoc/authenticationMechanism.adoc
closes #256 
Signed-off-by: Jimmy Wu <jimmywu0605@gmail.com>
=> fix typo in authentication dialog section

tck/app-mem-basic-decorate/src/main/java/ee/jakarta/tck/security/test/AuthenticationMechanismDecorator.java
This is instead of wrapping the HttpServletResponse.
=> Resolves #267 Update the decorator mechanism to use a HttpMessageContextWrapper

tck/app-mem-customform/pom.xml, tck/common/pom.xml, tck/old-tck/run/pom.xml, tck/pom.xml, tck/signaturetest/pom.xml
=> Update various versions of dependencies and plugins

tck/app-ldap/pom.xml, tck/app-ldap3/src/test/java/ee/jakarta/tck/security/test/AppLDAP3IT.java, tck/app-mem-basic-decorate/pom.xml
=> Fix copy paste errors in app names

tck/app-openid/src/test/java/ee/jakarta/tck/security/test/InvalidRedirectURIIT.java, tck/app-openid/src/test/java/ee/jakarta/tck/security/test/OpenIdTestUtil.java
=> Add nimbus jar to deployed war for OpenID app

api/src/main/java/module-info.java
Types of these appear within the method signatures of this API.
=> Require transitive for servlet, authentication and json in module-info

tck/common/src/main/java/ee/jakarta/tck/security/test/ArquillianBase.java, tck/common/src/main/java/ee/jakarta/tck/security/test/Assert.java, tck/pom.xml
* Option to always print responses when using *FromServer methods
* Assert variant that checks the default servlets used by tests are not accessed
=> Add conveniences

api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanismHandler.java
The current description was too vague and not using the correct CDI terminology.
=> Clarify the mandated behaviour of the mechanism handler.

tck/pom.xml
Set API version to 4.0.0-SNAPSHOT - API must be compiled locally until we release M2
=> Add new test modules to main pom

api/src/main/java/jakarta/security/enterprise/SecurityContext.java, api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanismHandler.java, api/src/main/java/jakarta/security/enterprise/identitystore/InMemoryIdentityStoreDefinition.java
Since tags, update year in license, add two forgotten attributes
=> Tidying up API before proposed final
