jakartaee/security

README.md

Travis was configured on the Java EE repository. It doesn't reflect the build status of the current repository.

Removed obsolete Travis badge

---

src/main/java/javax/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanismWrapper.java
src/main/java/javax/security/enterprise/identitystore/IdentityStoreWrapper.java

#79 Added wrappers for HttpAuthenticationMechanism and IdentityStore

---

src/main/java/javax/security/enterprise/authentication/mechanism/http/AutoApplySession.java
src/main/java/javax/security/enterprise/authentication/mechanism/http/LoginToContinue.java
src/main/java/javax/security/enterprise/authentication/mechanism/http/RememberMe.java
src/test/java/org/glassfish/security/AnnotationLiteralTest.java

PR for #82 Add annotation literals for built-in annotations.
The following annotations made sense to have literals for them:
* AutoApplySession
* LoginToContinue
* RememberMe
There are the interceptor binding annotations. The *Definition annotations are just plain (no CDI) annotations and don't need literals. We don't have qualifiers in EE Security (yet).

82 annotation literals

---

src/main/java/javax/security/enterprise/SecurityContext.java

Fixed Javadoc ommission

---

pom.xml

Signed-off-by: Guillermo González de Agüero <z06.guillermo@gmail.com>

Updated artifactId and groupId

---

pom.xml

Jakarta spec fixes

---

pom.xml

Jakarta POM fixes

---

README.md

Update readme with description and API path

---

pom.xml
spec/pom.xml

Small updated to pom - clarify name for parent and relax JDK8 restr.

---

spec/src/main/asciidoc/authenticationMechanism.asciidoc
spec/src/main/asciidoc/bibliography.asciidoc
spec/src/main/asciidoc/concepts.asciidoc
spec/src/main/asciidoc/identityStore.asciidoc
spec/src/main/asciidoc/license.asciidoc
spec/src/main/asciidoc/preface.asciidoc
spec/src/main/asciidoc/security-spec.adoc
spec/src/main/asciidoc/securityContext.asciidoc

Replaced JCP terms. All but some `JASPIC` and one `JACC`links.
Any idea of a short term to replace them?

Replaced JCP terms (fixes #147)

---

spec/src/main/asciidoc/authenticationMechanism.asciidoc
spec/src/main/asciidoc/bibliography.asciidoc

JASPIC -> AUTH
JACC -> AUTHZN
What do you think?

Proposed fix for #149

---

api/pom.xml
api/src/main/java/jakarta/security/enterprise/AuthenticationStatus.java
api/src/main/java/jakarta/security/enterprise/SecurityContext.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/AutoApplySession.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/CustomFormAuthenticationMechanismDefinition.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanism.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/HttpMessageContext.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/HttpMessageContextWrapper.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/RememberMe.java
api/src/main/java/jakarta/security/enterprise/identitystore/IdentityStore.java
api/src/main/java/jakarta/security/enterprise/identitystore/IdentityStoreHandler.java
api/src/main/java/jakarta/security/enterprise/identitystore/RememberMeIdentityStore.java
api/src/main/java/jakarta/security/enterprise/package-info.java
pom.xml

#156 Update to Jakarta dependencies

---

api/pom.xml
pom.xml
spec/pom.xml

#156 Prepare for RC2 release

---

api/src/main/java/jakarta/security/enterprise/CallerPrincipal.java

#102 Make CallerPrincipal Serializable (again)

---

api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/AutoApplySession.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanismWrapper.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/LoginToContinue.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/RememberMe.java

Also provide javadoc and update copyright to make plugin happy

#193 Add default constructor to wrapper so it can be proxied

---

api/src/main/java/jakarta/security/enterprise/SecurityContext.java

Not worth it to have a formal Enterprise Beans dependency just to
display a link in JavaDoc.

Fix javadoc link

---

api/src/main/java/jakarta/security/enterprise/identitystore/openid/OpenIdContext.java

These methdods are redundant, but also not entirely correct as they
only return the name/groups assigned by OpenID and not the actual ones.

Remove redundant methods

---

tck/app-openid2/pom.xml
tck/app-openid3/pom.xml

More stable startups of Tomcat immediately following shutdowns
* app-openid3 tests failed on some machines if executed right after app-openid2 because shutdown script for app-openid2 ended, but shutdown was still in progress while app-openid3 tried to start Tomcat again
* catalina.sh contains ways to stabilize that, so we can use them
* Updated Tomcat from 9.0.60 to 9.0.63
* whitespace cleanup

Stabilized tomcat tests

---

tck/pom.xml

These can be added back later once we have a compatible WildFly version
to reference.

Remove the WildFly profiles from the TCK.

---

tck/app-openid/src/main/java/ee/jakarta/tck/security/test/server/OidcProvider.java
tck/app-openid/src/main/resources/jsonwebkeys.json
tck/app-openid/src/test/java/ee/jakarta/tck/security/test/OpenIdTestUtil.java

for #277 
- update OidcProvider to use SignedJWT
- update the `/token` endpoint to use SignedJWT with RS256 instead of PlainJWT to comply with oidc spec
- create the `/certs` endpoint to return the jwk set containing the jwk used to sign the id token in the `/token` endpoint
- additionally updated the `/userinfo` endpoint to also return a preferred_username, since the default callerNameClaim is preferred_username, but it is currently not sent in the access token, id token, nor userinfo (i put it into the user info, since that's where it's inserted in `app-openid2`)

update mock OP to use SignedJWT and return preferred_username in user info

---

api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/openid/OpenIdProviderMetadata.java

hello,
i'm proposing to change the `userinfoEndpoint` in `OpenIdProviderMetadata` from `Required` to `Optional` in its javadoc.
i think this will make it more aligned with the authentication mechanism spec since:
1. it is not one of the required values under the `Metadata configuration` section.
> The following metadata values are required (since they are defined as required by the OpenID Specification):
> 
> Authorization endpoint
> 
> Token endpoint
> 
> JWKS URI
> 
> Issuer of the tokens
> 
> Supported Subject types
> 
> Supported Response types
> 
> Supported Id Token Signing Algorithms
https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#metadata-configuration
2. not all op's support the user info endpoint.
> An implementation may …

change userinfoEndpoint in OpenIdProviderMetadata to optional

---

tck/app-ldap/src/main/java/ee/jakarta/tck/security/test/Servlet.java
tck/app-ldap3/src/main/resources/test.ldif

Fixes #275 Provide explicit group search filter according to challenge
Fixes #276  ldap-3 uses seeAlso (memberOf) in LDIF without defining those groups
Test depended on Soteria specific default.

Fix ldap issues in TCK

---

tck/app-openid/src/main/java/ee/jakarta/tck/security/test/server/OidcProvider.java
tck/app-openid/src/test/java/ee/jakarta/tck/security/test/OpenIdTestUtil.java

Signed-off-by: Teddy J. Torres <teddyjtorres@hotmail.com>
For issue #277
Allows a profile to specify that it needs to use an https port with the `oidcProviderUsesHttps` property and the port number with the `oidcProviderHttpsPort` property for the provider in the app-openid tests as follows,
```
<plugins>
<plugin>
<artifactId>maven-failsafe-plugin</artifactId>
<version>${maven.test.version}</version>
<configuration>
<systemPropertyVariables>
<wlp>${wlp.home}</wlp>
<webServerHost>localhost</webServerHost>
<webServerPort>9080</webServerPort>
<javax.net.ssl.trustStore>${wlp.home}/usr/servers/security-tck/resources/security/key.jks</javax.net.ssl.trustStore>
<javax.net.ssl.trustStorePassword>CHANGEIT</javax.net.ssl.trustStorePassword>
<oidcProviderUsesHttps>true</oidcProviderUsesHttps> …
```

Allow profile to specify https port for issue #277

---

tck/app-openid2/pom.xml
tck/app-openid3/pom.xml

This is specifically important for the TCK to be able to run on the latest maven versions.

Update keytool-maven-plugin to 1.7

---

api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/BasicAuthenticationMechanismDefinition.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/CustomFormAuthenticationMechanismDefinition.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/FormAuthenticationMechanismDefinition.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanism.java
api/src/main/java/jakarta/security/enterprise/authentication/mechanism/http/OpenIdAuthenticationMechanismDefinition.java
tck/app-custom-authentication-mechanism-handler2/pom.xml
tck/app-custom-authentication-mechanism-handler2/src/main/java/ee/jakarta/tck/security/test/BasicAuthenticationMechanism2.java
tck/app-custom-authentication-mechanism-handler2/src/main/java/ee/jakarta/tck/security/test/BasicAuthenticationMechanism3.java
tck/app-custom-authentication-mechanism-handler2/src/main/java/ee/jakarta/tck/security/test/CustomAuthenticationMechanismHandler.java
tck/app-custom-authentication-mechanism-handler2/src/main/java/ee/jakarta/tck/security/test/ProtectedServlet1.java
tck/app-custom-authentication-mechanism-handler2/src/main/java/ee/jakarta/tck/security/test/ProtectedServlet2.java
tck/app-custom-authentication-mechanism-handler2/src/main/java/ee/jakarta/tck/security/test/ProtectedServlet3.java
tck/app-custom-authentication-mechanism-handler2/src/main/java/ee/jakarta/tck/security/test/TestIdentityStore.java
tck/app-custom-authentication-mechanism-handler2/src/main/webapp/WEB-INF/beans.xml
tck/app-custom-authentication-mechanism-handler2/src/test/java/ee/jakarta/tck/security/test/AppCustomAuthenticationMechanismHandler2IT.java

Fixes #311 
This will add qualifiers to the build-in authentication mechanisms, with the ability for users to provide their own.

Add qualifiers to build-in authentication mechanism beans

---

tck/app-securitycontext-customprincipal/src/main/java/ee/jakarta/tck/security/test/CustomPrincipal.java

This is not strictly needed for the test itself, but better for the purpose of best practice demonstration.

Make the custom principal Serializable.

---

api/pom.xml

Specifically update to final versions of Jakarta 11 wave 1-4

Update versions in API pom

---

spec/src/main/asciidoc/concepts.adoc

modified:   spec/src/main/asciidoc/concepts.adoc
Addresses https://github.com/jakartaee/platform/pull/855#pullrequestreview-1931388280

On branch edburns-msft-jea-339-absorb-assertions-from-cdi-integration Built-in beans from CDI integration spec.

---

api/src/main/java/jakarta/security/enterprise/SecurityContext.java
spec/src/main/asciidoc/securityContext.adoc

This aligns the hasAccessToWebResource Javadoc with how it was intended to work and how it's covered by the TCK tests, as clarified by @arjantijms in https://github.com/jakartaee/security/pull/266#issuecomment-1219707736.
The `hasAccessToWebResource` method is intended to be aligned with the [WebResourcePermission](https://jakarta.ee/specifications/authorization/2.1/apidocs/jakarta.security.jacc/jakarta/security/jacc/webresourcepermission#%3Cinit%3E(java.lang.String,java.lang.String)), which is already mentioned in Javadoc. It interprets an empty list of HTTP methods as "all HTTP methods". So this PR clarifies that access to all HTTP methods is required if no method is provided as an argument.

Fixes #262: Clarify using hasAccessToWebResource with no methods

---

tck/app-openid2/pom.xml
tck/app-openid3/pom.xml
tck/pom.xml

* Failsafe 
- original milestone versions did not print stacktraces, just one line.
- Surefire report plugin should keep the same version
* The fix fixes the test side of the communication, GlassFish resolves same problem here: https://github.com/eclipse-ee4j/glassfish/pull/25662 . GF 7.0.x sets the password to system properties, that is the reason why it always worked.
```
mvn clean install -f tck -Dglassfish.version=7.1.0-SNAPSHOT -DtrustStore.suffix=p12 -Dglassfish.javax.net.debug=all
```

Fixed missing password to the GF truststore + Updated Failsafe
